# Generated by Django 3.2.16 on 2022-12-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Constellation',
            new_name='constellation',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Weapon',
            new_name='weapon',
        ),
        migrations.RenameField(
            model_name='constellation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voiceactor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Name',
            new_name='name',
        ),
    ]
